[common]
mid = 58
mname = "nn_server"
log_file = "../../log/nn_server.58.log"
save_path = "/userdata/mpp/disk"

[mqttc]
;baddr = "tcp://localhost:1883"
;qos = 0
;timeout = 100
;topic.cfg = "cfg"
;topic.cmd = "cmd"

[ch]
path = "/oem/smart-gw/chma/"

[dmqttc]
enable = true

[nn]
nn_path = "../"
notify_num = 1 ; max 20

[notify.0]
topic = "/dposter/58/cmd"
is_snd_pic = false
is_label = false

