[common]
mid = 200
mname = "nn_server"
log_file = "../../log/nn_server.200.log"
save_path = "/userdata/mpp/disk"

[mqttc]
baddr = "tcp://127.0.0.1:1883"
qos = 0
timeout = 100

[ch]
path = "/oem/smart-gw/chma/"

[dmqttc]
enable = true

[nn]
nn_path = "../"
notify_num = 1 ; max 20

[notify.0]
topic = "/dposter/200/cmd"
is_snd_pic = false
is_label = false
